export const LOADING = 'LOADING';
export const ERROR = 'ERROR';

export const LOGIN_SUCCEED = 'LOGIN_SUCCEED';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const REGISTER_SUCEED = 'REGISTER_SUCEED';
export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const FETCH_CART_LOADING = 'FETCH_CART_LOADING';
export const FETCH_CART_SUCCEED = 'FETCH_CART_SUCCEED';
export const FETCH_CART_FAILED = 'FETCH_CART_FAILED';
export const ADD_PRODUCT_TO_CART_BY_ID = 'ADD_PRODUCT_TO_CART_BY_ID';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';